services:
  - type: web
    name: stock-control
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://stock-control.onrender.com
      - key: APP_KEY
        value: base64:Cqxzq/lbn2n/zDNLRzdg73xDdxaVHto2zb3MQgqv8T0=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d3ml4v2dbo4c73av3g3g-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: stock_control_1otg
      - key: DB_USERNAME
        value: stock_control_1otg_user
      - key: DB_PASSWORD
        value: wv5ajanWQsDyIfzmUcya7SNabJaW5pWk
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: trombini.dev@gmail.com
      - key: MAIL_PASSWORD
        value: iouexirxrgipcqgz
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: trombini.dev@gmail.com
      - key: MAIL_FROM_NAME
        value: Laravel
